kind: ConfigMap
apiVersion: v1
metadata:
  name: appconfig
  namespace: apiv1
data:
  .env: |
    SERVER_NAME=apiv1.ops4cloud.fr
    WAITRESS_PORT=8888
    MONGO_DB_HOST=mongo
    MONGO_DB_port=27017
    MONGO_DB=flaskapi
    JWT_SECRET_KEY=nkejzcnzkejcnkzejcnzekcjnzec
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiv1
  namespace: apiv1
  labels:
    app: apiv1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apiv1
  template:
    metadata:
      labels:
        app: apiv1
    spec:
      containers:
      - name: apiv1
        imagePullPolicy: Always
        image: ops4cloud/flaskapi:main
        ports:
        - containerPort: 8888
        volumeMounts:
        - name: config-vol
          mountPath: /config
      volumes:
      - name: config-vol
        configMap:
            name: appconfig
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: apiv1
  labels:
    app: apiv1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apiv1
  template:
    metadata:
      labels:
        app: apiv1
    spec:
      containers:
      - name: mongo
        image: mongo:4.4.9
        ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    app: apiv1
spec:
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
  selector:
    app: apiv1
