version: "3.9"
    
services:
  mongo:
    hostname: mongo-service
    image: mongo:latest
    restart: always
  api:
    hostname: apiv1.ops4cloud.fr
    depends_on:
      - mongo
    image: europe-west1-docker.pkg.dev/gotoole-testing/flaskapi/flaskapi:latest
    ports:
      - "80:8888"
    restart: always
