name: flaskapi-ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run:
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Build docker flaskapi container
        run: docker build . --tag ops4cloud/flaskapi:$(date +%s)

      - name: Docker push to ops4cloud
        run: docker push ops4cloud/flaskapi:$(date +%s)
