name: flaskapi-ci

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          tags: ops4cloud/flaskapi:latest
      -
        name: Inspect
        run: |
          docker image inspect ops4cloud/flaskapi:latest
